2025-08-22 18:29:55,074 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:29:56,855 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:48:22,256 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:48:48,773 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:52:29,038 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 18:42:24,227 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 18:42:37,157 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 18:42:47,017 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 21:57:44,493 ERROR: Exception on /login [GET] [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py", line 83, in login
    return render_template('login.html')
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\templates\login.html", line 630, in top-level template code
    <form method="POST" action="{{ url_for('auth.resend_activation') }}">
    ^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.resend_activation'. Did you mean 'auth.activate' instead?
2025-08-23 21:57:56,087 ERROR: Exception on /login [GET] [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py", line 83, in login
    return render_template('login.html')
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\templates\login.html", line 630, in top-level template code
    <form method="POST" action="{{ url_for('auth.resend_activation') }}">
    ^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.resend_activation'. Did you mean 'auth.activate' instead?
2025-08-23 21:58:55,468 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:140]
2025-08-23 21:59:15,640 ERROR: Error preparando datos del usuario para localStorage: 'str' object has no attribute 'isoformat' [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py:55]
