2025-08-24 02:55:52,360 ERROR: Exception on /admin/reportes-mensuales [GET] [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py", line 20, in load_user
    return User.query.get(int(user_id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\query.py", line 1126, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return self.session._get_impl(
           ~~~~~~~~~~~~~~~~~~~~~~^
        mapper,
        ^^^^^^^
    ...<6 lines>...
        execution_options=self._execution_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\session.py", line 3874, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\engine\base.py", line 1810, in _execute_context
    conn = self._revalidate_connection()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\engine\base.py", line 676, in _revalidate_connection
    self._invalid_transaction()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\sqlalchemy\engine\base.py", line 666, in _invalid_transaction
    raise exc.PendingRollbackError(
    ...<4 lines>...
    )
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-08-24 02:56:45,409 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:178]
